### ISSUE TITLE
Reference issues inline in the spec

### ISSUE THREAD

**Issue by elf-pavlik** [w3c/activitystreams#29]
http://www.w3.org/2014/Process-20140801/#working-draft states:

> A Public Working Draft is published on the W3C's Technical Reports page [TR] for review, and for simple historical reference. For all Public Working Drafts a Working Group
> - SHOULD document outstanding issues, and parts of the document on which the Working Group does not have consensus, and
> -  MAY request publication of a Working Draft even if its content is considered unstable and does not meet all Working Group requirements.

I propose adding more significant issues inline to the spec, currently:
- [ ] #27 Reference context in examples

> ISSUE: currently all the examples don't include JSON-LD @context you can find working version at http://asjsonld.mybluemix.net/
- [ ] #24 as:Link from Linked Data perspective + comparing with hydra:Link

> ISSUE: as:Link uses same @id as resource it targets and most of its properties (except as:rel) describe the representation of a resource it targets not the link itself
- [ ] #23 as:Verb & as:verb possibly not needed

> ISSUE: as:Activity and as:PotentialAction use @type and/or as:verb to specify their type
- [ ] #36 as:verb - consequences of using blank node identifier (eg. _:post)

> ISSUE: using _blank node identifiers_ (eg. `_:post`) for values of as:verb can cause problems with comparing it across multiple JSON-LD documents even when they serialize single activity stream. Persisting activities with such blank node identifiers in triple stores will also result in them changing to different, not predictable, blank node identifiers. Also various processing algorithms will relabel blank nodes.
